# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0002_auto_20180411_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data_nascimento',
            new_name='data_ingresso',
        ),
    ]
