# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0005_materia_alunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencia.Aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencia.Materia')),
            ],
        ),
    ]
