# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0006_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='presente',
            field=models.NullBooleanField(),
        ),
    ]
