# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0008_auto_20180412_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='materias',
        ),
        migrations.AddField(
            model_name='materia',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='frequencia.Aluno'),
        ),
    ]
