# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0014_auto_20180423_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, to='frequencia.Aluno'),
        ),
    ]
