# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0018_auto_20180427_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='data',
            field=models.DateField(),
        ),
    ]
