# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-23 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0019_auto_20180427_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
