# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0020_aluno_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='observacao',
        ),
    ]
