# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0021_remove_nota_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valorNota',
            field=models.FloatField(),
        ),
    ]
