# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='observacao',
            field=models.TextField(default='', max_length=100),
        ),
    ]
